# Generated by Django 4.1.5 on 2023-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/directors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/posters/'),
        ),
    ]
