# Generated by Django 4.1.5 on 2023-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0002_director_picture_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, related_name='directors', to='filmwho.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='filmwho.director'),
        ),
    ]
