# Generated by Django 4.1.5 on 2023-01-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0004_alter_director_id_alter_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='id',
            new_name='director_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='movie_id',
        ),
    ]
