# Generated by Django 4.1.5 on 2023-01-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0005_rename_id_director_director_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.TextField(max_length=15),
        ),
    ]
