# Generated by Django 4.1.5 on 2023-01-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0006_alter_movie_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
