# Generated by Django 4.1.5 on 2023-01-24 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0007_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
