# Generated by Django 4.1.5 on 2023-01-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmwho', '0008_movie_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
